#配置端口号
server:
  port: 80
#配置日志级别
logging:
  level:
    root: warn
#配置domain数据
enterprise:
  name: jbh
  age: 21
  tel: 18200000
  subject:
    - java
    - python
    - c++
    - 随便什么
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms